//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_RESIDENCIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_RESIDENCIAL()
        {
            this.CAT_INMUEBLE = new HashSet<CAT_INMUEBLE>();
            this.CAT_HABITACIONAL = new HashSet<CAT_HABITACIONAL>();
        }
    
        public int ID_RESIDENCIAL { get; set; }
        public string RESIDENCIAL { get; set; }
        public bool ACTIVO { get; set; }
        public string ABREVIATURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_INMUEBLE> CAT_INMUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_HABITACIONAL> CAT_HABITACIONAL { get; set; }
    }
}
