//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_INMUEBLE
    {
        public int ID_INMUEBLE { get; set; }
        public int ID_HABITACIONAL { get; set; }
        public string NUMEXT { get; set; }
        public string NUMINT { get; set; }
        public string PROPIETARIO { get; set; }
        public string EMAIL { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CAT_HABITACIONAL CAT_HABITACIONAL { get; set; }
    }
}
