//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_INMUEBLE
    {
        public int ID_INMUEBLE { get; set; }
        public string INMUEBLE { get; set; }
        public int NUMEROEXT { get; set; }
        public string NUMEROINT { get; set; }
        public bool ACTIVO { get; set; }
        public int ID_RESIDENCIAL { get; set; }
    
        public virtual CAT_RESIDENCIAL CAT_RESIDENCIAL { get; set; }
    }
}
